name: FastAPI CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Необходимо для возможности пушить изменения обратно

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install flake8 black isort mypy pytest

      - name: Run isort (автоформатирование импортов)
        run: isort app/

      - name: Run Black (автоформатирование кода)
        run: black app/

      - name: Commit and push formatting changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || (git commit -m "Autoformat code with Black and isort" && git push)

      - name: Lint with flake8
        run: flake8 app/

      - name: Type checking with mypy
        run: mypy app/

      - name: Run tests with pytest
        run: pytest app/tests/
