name: FastAPI CI

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install flake8 black isort mypy pytest autoflake sqlalchemy2-stubs types-aiosqlite
          pip install flake8-black flake8-isort  # Добавляем плагины для совместимости
      
      - name: Create config files
        run: |
          # Создаем конфиг для flake8, совместимый с Black
          echo -e "[flake8]\nmax-line-length = 88\nextend-ignore = E203, W503\nper-file-ignores =\n    __init__.py: F401" > .flake8
          echo -e "[isort]\nprofile = black\nline_length = 88" > .isort.cfg
          echo -e "[mypy]\nplugins = sqlalchemy.ext.mypy.plugin" > mypy.ini
      
      - name: Create init files
        run: |
          echo -n > app/__init__.py
          echo -n > app/tests/__init__.py
      
      - name: Remove unused imports
        run: |
          autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports -r app/
      
      - name: Fix blank lines at end of files
        run: |
          find app/ -type f -name "*.py" -exec sed -i -e :a -e '/^\n*$/{$d;N;ba' -e '}' {} \;
      
      - name: Autoformat imports with isort
        run: isort app/
      
      - name: Autoformat code with Black
        run: black app/
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Clean code: fix formatting and init files [skip ci]"
            git pull --rebase
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi
      
      - name: Lint with flake8
        run: |
          flake8 app/ --max-line-length=88 --extend-ignore=E203,W503
      
      - name: Type checking with mypy
        run: |
          mypy app/ --config-file=mypy.ini
      
      - name: Run tests with pytest
        run: |
          pytest app/tests/ -v --cov=app --cov-report=xml
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
