name: FastAPI CI

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create init files
        run: |
          touch app/__init__.py
          touch app/tests/__init__.py
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install flake8 black isort mypy pytest autoflake
          pip install -e .
      
      - name: Remove unused imports
        run: |
          autoflake --in-place --remove-all-unused-imports --ignore-init-module-imports -r app/
      
      - name: Autoformat imports with isort
        run: isort app/
      
      - name: Autoformat code with Black
        run: black app/
      
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Add init files and fix imports [skip ci]"
            git pull --rebase
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          fi
      
      - name: Lint with flake8
        run: flake8 app/
      
      - name: Type checking with mypy
        run: mypy app/
      
      - name: Run tests with pytest
        run: pytest app/tests/
