name: FastAPI CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Чтобы можно было пушить обратно

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install flake8 black isort mypy pytest

      - name: Lint with flake8
        run: flake8 app/

      - name: Autoformat code with black and isort
        run: |
          black app/
          isort app/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          # Проверяем, есть ли изменения
          git diff --cached --quiet || (git commit -m "Autoformat by GitHub Actions" && git push)

      - name: Type checking with mypy
        run: mypy app/

      - name: Run tests with pytest
        run: pytest app/tests/
