name: FastAPI CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Lint with flake8
        run: flake8 app/

      - name: Check formatting with black
        run: black --check app/

      - name: Check import order with isort
        run: isort app/ --check-only

      - name: Type checking with mypy
        run: mypy app/

      - name: Run tests with pytest
        run: pytest app/tests/
